name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: dtolnay/rust-toolchain@master
        with:
          # Must be kept in sync with Cargo.toml.
          toolchain: '1.96'
          components: clippy,rustfmt
      - name: Set up dependencies
        run: |
            sudo add-apt-repository ppa:dqlite/dev -y
            sudo apt update
            sudo apt install -y libsqlite3-dev liblz4-dev libuv1-dev \
                              linux-libc-dev lcov libdqlite1.18-unstable-dev # TODO: remove -unstable when stable is available
      
      - uses: ./.github/actions/cargo-lint
      - name: Run tests
        uses: ./.github/actions/cargo-test

