name: Build PPA source packages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    environment:
      name: ppa
    strategy:
      fail-fast: false
      matrix:
        target:
          - jammy
          - noble
          - resolute
    steps:
      - name: Setup dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq devscripts dput-ng git gnupg

      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: dtolnay/rust-toolchain@master
        with:
          # Must be kept in sync with Cargo.toml.
          toolchain: '1.91'
          components: clippy,rustfmt

      - name: Setup GPG signing key
        env:
          PPA_SECRET_KEY: ${{ secrets.PPA_SECRET_KEY }}
        run: |
          echo "$PPA_SECRET_KEY" > private-key.asc
          gpg --import --batch private-key.asc
          rm -f private-key.asc

      - name: Build source package
        env:
          DEBFULLNAME: "GitHub Actions"
          DEBEMAIL: "dqlitebot@lists.canonical.com"
          TARGET: ${{ matrix.target }}
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          DESCRIBE="$(git describe --tags --long --match 'v*')"
          BASE_VERSION="${DESCRIBE#v}"
          BASE_VERSION="${BASE_VERSION%%-*}"
          COMMITS="$(printf '%s\n' "$DESCRIBE" | cut -d- -f2)"
          GIT_SHA="$(printf '%s\n' "$DESCRIBE" | cut -d- -f3 | sed 's/^g//')"
          if [ "$COMMITS" = "0" ]; then
            VERSION="$BASE_VERSION"
          else
            VERSION="${BASE_VERSION}+git${COMMITS}.g${GIT_SHA}"
          fi

          dch --create \
              --distribution "${TARGET}" \
              --package dqlite-utils \
              --newversion "${VERSION}~${TARGET}1" \
              "Automatic build from GitHub (${GITHUB_SHA})"
          debuild -S -sa -d -k"${{ vars.PPA_PUBLIC_KEY }}"

      - name: Upload to Launchpad
        run: |
          (cd .. && dput -U -u ppa:dqlite/dqlite *.changes)
